name: Dull
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.13', '1.14' ]
    name: Go ${{ matrix.go }}

    steps:
      - name: Install sytem dependencies
        run: |
          sudo apt update
          sudo apt install -y libgl1-mesa-dev xorg-dev xvfb

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          xvfb-run go test -tags headless ./...
